### ISSUE TITLE
Add Federico Kunze to people data

### ISSUE THREAD

**Issue by fedekunze** [tendermint/aib-data#131]
Name: Federico Kunze
Role: Software Engineer
Bio: Federico Kunze is an alumni from Blockchain at Berkeley (B@B) where in 2017 he joined an external consulting team working to build a decentralized license marketplace for Qualcomm and created content for the Executive Education program for Fortune 500 companies. He's now also advising the Chilean ministry of economy in public sector blockchain use cases and co-founded the Chilean Blockchain Industry Association (a.k.a [CryptoChile](http://cryptochile.io/)).

email: federico@tendermint.com
GitHub: [https://github.com/fedekunze](https://github.com/fedekunze)
LinkedIn: [https://www.linkedin.com/in/fekunze/](https://www.linkedin.com/in/fekunze/)
Twitter: [https://twitter.com/fekunze](https://twitter.com/fekunze)

**Comment by nylira** [comment]
Resolved!
