### ISSUE TITLE
use the ecosystem.json in the tendermint docs

### ISSUE THREAD

**Issue by zramsay** [tendermint/aib-data#15]
this file: https://github.com/tendermint/aib-data/blob/master/json/ecosystem.json
should be used to create: https://github.com/tendermint/tendermint/blob/master/docs/ecosystem.rst#abci-applications
which needs a prettified table. some css in the docs is used [here](https://github.com/tendermint/tendermint/tree/master/docs/_static) and [here](https://github.com/tendermint/tendermint/tree/master/docs/_templates) then rendered in this page: https://raw.githubusercontent.com/tendermint/tendermint/master/docs/app-development.rst

The first part is to pull the data from the `ecosystem.json` which will need a re-work [here](https://github.com/tendermint/tendermint/blob/master/docs/conf.py#L174-L197)

**Comment by nylira** [comment]
Discussed with @zramsay and it's easiest to use the /ecosystem on tendermint.com for now. A fixed version is in this PR: https://github.com/tendermint/tendermint.github.io/pull/126
