### ISSUE TITLE
technical partnership manager is more of a support role

### ISSUE THREAD

**Issue by jolesbi** [tendermint/aib-data#150]

**Comment by gamarin2** [comment]
-Support partners in the implementation of their projects using products from the Tendermint / Cosmos stack.
-Help with developer adoption by supporting projects using Tendermint and Cosmos products.
-Participate in developer discussion forums and work to improve the usability based on user feedback.
 -Provide feedback to the SDK team based on the needs of the partner projects.

I think everyone agreed on slack that "Ecosystem Developer" is a good Title for this position. Basically we need someone at the application level of our tech stack. Someone that knows how to develop app/modules on top of our various frameworks. Not someone that will work on the framework themselves, but rather use them and help other use them as well.
