### ISSUE TITLE
short descriptions on careers page

### ISSUE THREAD

**Issue by ebuchman** [tendermint/aib-data#164]
It would be nice if we could communicate a little more about each job (maybe some kind of "tags") on the main careers page. It would make it easier for people landing on our careers page to know what jobs might apply to them, without having to know what SDK or Databases or Language means. 

Thoughts ? 

This was motivated by wanting to post a position for someone who could help maintain ABCI servers in many languages. It would be `Senior Software Engineer - ABCI` or `Senior Software Engineer - Languages`, but really its a position for someone that knows lots of languages and wants to write in all of them. Is there a good word for that?

**Comment by ebuchman** [comment]
Polyglot!

**Comment by nylira** [comment]
I think this is a great idea. What we need to do is add metadata fields (with YAML or something else) to the top of each job markdown file. Like this:

```
~~~
title: Job Title
flags: go, crypto, database
excerpt: We are hiring a go crypto database expert to blah blah blah our blahs. Blah!
~~~
```
And then we load the combined YAML/Markdown file in our website and split the file and parse the two components individually.

**Comment by jolesbi** [comment]
good idea! some sorting would be nice! let's include location too!
