### ISSUE TITLE
Add Alexander Simmerl to people data

### ISSUE THREAD

**Issue by Liamsi** [tendermint/aib-data#180]
cc @xla

**Comment by xla** [comment]
![approve](http://i0.kym-cdn.com/entries/icons/original/000/010/269/Screen_shot_2012-05-10_at_4.38.30_PM.png)

**Comment by nylira** [comment]
@xla please give us a portrait photo, brief bio, and then any of the following: twitter, github, keybase, linkedin, personal website.

**Comment by nylira** [comment]
@xla please PM me this info and I can get you up there :)

**Comment by xla** [comment]
@nylira Sorry for the delay. I'd prefer to use my avatar instead of a real picture of me: https://avatars1.githubusercontent.com/u/1585

github: https://github.com/xla
keybase: https://keybase.io/xla
twitter: https://twitter.com/xla
linkedin: what year is this?

**Comment by xla** [comment]
@zramsay Does it mean I'm not gonna be included?

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint.com/issues/179

**Comment by zramsay** [comment]
no, just moved the issue to the website repo ^

**Comment by xla** [comment]
😻
