### ISSUE TITLE
Use AIB data for Game Of Steaks Scorecard Badges

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/aib-data#197]
After talking with @zmanian in the Validators meeting the requirements for the Scorecard above and beyond what the current feature set of Explorer would be the following:

- Ability to sort validator set by voting power/stake
- Ability to show badges/achievements (branding here TBD)

This means that all we need is a way to store an easily editable JSON blob that can be served to show the badges (which this repo provides)

Let's use this issue as a place to discuss:
- JSON Structure
- Which badges we want

**Comment by jackzampolin** [comment]
cc @nylira @Chjango @Michelle-L

**Comment by zramsay** [comment]
i don't know where this would go but it isn't this repo anymore
