### ISSUE TITLE
Notice: Repository Deprecation

### ISSUE THREAD

**Issue by nylira** [tendermint/aib-data#198]
This repository will be dissolved in favor of moving data directly into the website repos. Please don't make any more changes to this repo unless absolutely necessary, the content will be moved over the next week.

* allinbits.com will be removed
* tendermint data should go into tendermint/tendermint.com/content
* cosmos data should go into cosmos/cosmos.network/content
* explorer data should go into cosmos/explorer/content @jackzampolin

**Comment by zramsay** [comment]
the `ecosystem.json` should go in the tendermint repo (docs/ directory) and included in the docs build sequence

**Comment by nylira** [comment]
https://github.com/tendermint/tendermint/pull/1926
