### ISSUE TITLE
add a .json file that lists versions we expect to work together

### ISSUE THREAD

**Issue by zramsay** [tendermint/aib-data#31]
this file can be read from docs/website/wherever and updated every release

from: https://github.com/tendermint/coding/issues/29

and see also: 
- https://github.com/tendermint/ethermint/issues/318
- https://github.com/tendermint/tendermint/issues/1172

**Comment by faboweb** [comment]
Just an idea: Could we maybe version matching versions the same?

Example:
- cosmos-ui 0.5.0
- gaia 0.5.0

And then use minor version increments for non breaking changes.
