### ISSUE TITLE
where is /community

### ISSUE THREAD

**Issue by zramsay** [tendermint/aib-data#78]
we used to have either:

tendermint.com/community OR
cosmos.network/community

neither of these exist anymore

**Comment by nylira** [comment]
Dragging @jolesbi into this. We had a /community page, but we decided that the footer held enough information about the community.

**Comment by zramsay** [comment]
was the decision documented somewhere? who was responsible for updating all the docs that had added that link?

**Comment by martindale** [comment]
We should also make sure to `302` or `301` resources being removed to their new locations (or some comparable replacement).  Old links shouldn't just 404!

**Comment by jolesbi** [comment]
if my memory serves me well, the community page contained the same information that is now in our footer. this was done as part of the redesign in november.

**Comment by nylira** [comment]
@jessysaurusrex for security purposes -- are the community links in the footer good enough, or should we have an official /community page?

**Comment by zramsay** [comment]
IMO, leave links in the footer but if it doesn't add maintainance overhead, it would be great to have `/community` because it's extremely useful to have all our repo README's and docs (where applicable) point to it, rather than to just a site where you gotta scroll down to the footer

**Comment by jessysaurusrex** [comment]
@nylira For now, community links suffice-- for security, the most important thing to make sure we have is the /security page. To @zramsay's point though, a page may be more usable for people looking for information.

**Comment by jolesbi** [comment]
> all our repo README's and docs

i don't think this was in the footer. irregardless 😉- is this the kind of information that belongs on a `/community` page? makes sense that it should live somewhere.

i don't have strong feelings about how to roll this out. but good idea!

**Comment by nylira** [comment]
I'll create a Community page again for Tendermint and Cosmos

**Comment by nylira** [comment]
It's here: https://cosmos.network/community

**Comment by zramsay** [comment]
merci!
