### ISSUE TITLE
Test every URL to make sure it still works

### ISSUE THREAD

**Issue by nylira** [tendermint/aib-data#94]
We probably have a slew of broken URLs through our documents, either through typos or the churn of the internet.

- [x] test urls in the JSON and markdown content of `aib-data`
- [x] test every url in `tendermint.com`
- [x] test every url in `cosmos.network`

**Comment by zramsay** [comment]
should a link-checked be added to the CI?

**Comment by faboweb** [comment]
That is a great idea @zramsay. Do you know how to do this?

**Comment by zramsay** [comment]
https://github.com/wummel/linkchecker

looks a bit out of date but a google search turned up plenty of options
